import os

print("'API_GOOGLE_SUBDOMAIN_URL'",end=':')
print(os.getenv('API_GOOGLE_SUBDOMAIN_URL'))
print("'API_GOOGLE_LOCAL'",end=':')
print(os.getenv('API_GOOGLE_LOCAL'))
print("'DJANGO_SECRET_KEY'",end=':')
print(os.getenv('DJANGO_SECRET_KEY'))
print("'DJANGO_DEBUG'",end=':')
print(os.getenv('DJANGO_DEBUG'))
print("'DJANGO_ALLOWED_HOSTS'",end=':')
print(os.getenv('DJANGO_ALLOWED_HOSTS').split(';') if os.getenv('DJANGO_ALLOWED_HOSTS') != None else None)
print("'DATABASE_ENGINE'",end=':')
print(os.getenv('DATABASE_ENGINE'))
print("'DATABASE_NAME'",end=':')
print(os.getenv('DATABASE_NAME'))
print("'DATABASE_USER'",end=':')
print(os.getenv('DATABASE_USER'))
print("'DATABASE_PASSWORD'",end=':')
print(os.getenv('DATABASE_PASSWORD'))
print("'DATABASE_HOST'",end=':')
print(os.getenv('DATABASE_HOST'))
print("'DATABASE_PORT'",end=':')
print(os.getenv('DATABASE_PORT'))
print("'EMAIL_HOST'",end=':')
print(os.getenv('EMAIL_HOST'))
print("'EMAIL_TSL'",end=':')
print(os.getenv('EMAIL_TSL'))
print("'EMAIL_PORT'",end=':')
print(os.getenv('EMAIL_PORT'))
print("'EMAIL_HOST_USER'",end=':')
print(os.getenv('EMAIL_HOST_USER'))
print("'EMAIL_HOST_PASSWORD'",end=':')
print(os.getenv('EMAIL_HOST_PASSWORD'))
